version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    command: python .
    environment:
      DB_URL: postgresql://admin:admin@db:5432/admin
    volumes:
      - "./app:/app:ro"
    depends_on:
      - db

  db:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin

  nginx:
    image: nginx:1.25.3-alpine3.18
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - "./conf.d:/etc/nginx/conf.d:ro"
